### ISSUE TITLE
Fix problems deteced by socket.dev

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/html-to-react#47]
Today @davidmehren had a look at this project with socket.dev and there are some problems with it. We should fix those.

See also:
https://socket.dev/npm/package/@hedgedoc/html-to-react/overview/1.4.1

**Comment by mrdrogdrog** [comment]
Fixed since https://github.com/hedgedoc/html-to-react/commit/e0c2a8cc631295b5b44a72ad98ec357f1f8f7e27

**Comment by DerMolly** [comment]
Technically there is no new release for the software so the problem is not fixed for the version von npm…

**Comment by mrdrogdrog** [comment]
I released a new version.

**Comment by DerMolly** [comment]
There seems to be still a problem:

https://socket.dev/npm/package/@hedgedoc/html-to-react/overview/1.4.3
